name: Update RSS Feed

on:
  schedule:
    # http://pubs.opengroup.org/onlinepubs/7908799/xcu/crontab.html
    # 15:00 UTC = 00:00 KST
    - cron: "0 15 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Create a new rss.xml file
      run: pnpm generate
      
    - name: Commit to repository
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update RSS (engineering.ab180.co)
